export const interests = [
    'Web Development',
    'Web Applications',
    'Cyber Security',
    'Project Management',
    'System Design',
    'Hacking',
    'Hardware Troubleshooting',
    'Firmware Engineering',
    'Embedded Engineering',
    'Machine Learning',
    'Agentic AI',
    'AI Automation',
    'Media Design',
    'Mentoring',
    'Mobile Development',
    'Desktop Development',
    'Kernel Engineering',
    'Game Development',
    'Open Source',
    'SaaS',
    'PaaS',
    'IaaS',
    'Developer Tools',
    'Collaboration',
    'Networking',
    'System Administration',
    'Cloud Development',
    'Applications Development',
    'Legacy Systems',
    'Robotics',
    'Web3',
    'Blockchain',
    'Competitive Programming',
    'Hackathons',
    'Linux',
    'Windows',
    'MacOS',
    'Android',
    'Fullstack Development',
    'Backend Development',
    'Frontend Development',
    'AI Development',
    'ML Development',
    'Mathematics Programming',
];