export const skills = [
    'HTML',
    'CSS',
    'Bootstrap',
    'Tailwind',
    'jQuery',
    'JavaScript',
    'TypeScript',
    'Java',
    'SpringBoot',
    'C#',
    '.NET Core',
    'ASP .NET',
    'ASP WebForms',
    'C',
    'Embedded Systems',
    'Firmware',
    'C++',
    'Unity',
    'Godot',
    'GDScript',
    'Python',
    'Django',
    'Flask',
    'Ruby',
    'PHP',
    'Ruby on Rails',
    'Laravel',
    'CodeIgniter',
    'UI/UX',
    'Automation',
    'AI/ML',
    'Cybersecurity',
    'Project Management',
    'QA Testing',
    'Figma',
    'Photoshop',
    'AI Automation',
    'System Design',
    'Competitive Programming',
    'AWS',
    'Azure',
    'GCP',
    'Docker',
    'Podman',
    'CI/CD',
    'DevOps',
    'Kotlin',
    'React Native',
    'Swift',
    'Electron',
    'MAUI',
    'SQL',
    'MySQL',
    'PostgreSQL',
    'MSSQL',
    'NoSQL',
    'Firebase',
    'Supabase',
    'NextJS',
    'ReactJS',
    'VueJS',
    'AngularJS',
    'Svelte',
    'Bash',
    'Rust',
    'Zig',
    'Lua',
    'NodeJS',
    'Git',
    'Wordpress',
    'ThreeJS',
    'Go',
    'Golang',
    'Elixir',
];